[project]
name = "adafruit-im-alive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "adafruit-io>=2.8.0",
    "pydantic>=2.11.4",
    "pydantic-settings>=2.9.1",
]
